In [20]:
import numpy as np

In [2]:
numeros_primos=[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
numeros_primos

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

In [3]:
array_primos = np.array(numeros_primos)
array_primos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [4]:
array_ceros = np.zeros(10)
array_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
array_numeros = np.arange(10)
array_numeros

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
array_pares = np.arange(0,20,2)
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
array_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [17]:
array_impares = array_pares+1
array_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
array_primos.sum()

129

In [21]:
array_primos.mean()

12.9

In [22]:
array_primos.var()

73.28999999999999

In [26]:
array_fibonacci= np.array([55,0,144,1,21,89,5,8,13,1,34,3,2])
array_fibonacci

array([ 55,   0, 144,   1,  21,  89,   5,   8,  13,   1,  34,   3,   2])

In [27]:
np.sort(array_fibonacci)

array([  0,   1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144])

In [33]:
-np.sort(-array_fibonacci)

array([144,  89,  55,  34,  21,  13,   8,   5,   3,   2,   1,   1,   0])

In [41]:
A=np.arange(0,20,2).reshape(2,5)
A

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [42]:
A[0,0]

0

In [43]:
A[1,3]

16

In [44]:
A[1,:]

array([10, 12, 14, 16, 18])

In [45]:
A[:,3]

array([ 6, 16])

In [46]:
array_fibonacci<20

array([False,  True, False,  True, False, False,  True,  True,  True,
        True, False,  True,  True])

In [47]:
array_fibonacci[array_fibonacci<20]

array([ 0,  1,  5,  8, 13,  1,  3,  2])